import {useEffect,useState,lazy,Suspense} from 'react';
import type {CSSProperties} from 'react';
import type {Catalog,Property,Lot} from './model';
import {emptyCatalog,money} from './model';
import {api} from './api';
import hero from './assets/hero-casa.webp';
import PlanView from './PlanView';
const MapView=lazy(()=>import('./MapView'));
export function Brand(){return <a className="brand" href="/" aria-label="Casa Mexino, inicio"><img className="brand-logo" src="/logo-casa-mexino.png?v=2" alt=""/><span className="brand-copy"><strong>Casa Mexino</strong><small>Gestión inmobiliaria</small></span></a>;}
function PropertyCard({p}:{p:Property}){return <a className="listing" href={`/propiedades/${p.id}`}><div className="listing-photo">{p.images[0]?<img src={p.images[0]} alt={p.title} loading="lazy"/>:<span>Sin fotografía</span>}<span className="tag">{p.operation} · {p.type}</span>{p.status!=='Disponible'&&<span className="status-tag">{p.status}</span>}</div><div className="listing-heading"><h3>{p.title}</h3><span aria-hidden>↗</span></div><p>{p.address||'Matehuala'}</p><div className="listing-bottom"><strong>{money(p.price)}{p.operation==='Renta'&&<small> / mes</small>}</strong><span>{p.area} m²</span></div></a>;}
export default function PublicPortal(){
  const [data,setData]=useState<Catalog>(emptyCatalog),[loading,setLoading]=useState(true),[error,setError]=useState(''),[retry,setRetry]=useState(0);
  const [q,setQ]=useState(''),[operation,setOperation]=useState(''),[type,setType]=useState(''),[max,setMax]=useState(''),[menu,setMenu]=useState(false),[selectedLot,setSelectedLot]=useState<Lot|null>(null),[lotStatus,setLotStatus]=useState('Todos'),[photo,setPhoto]=useState(0),[heroSlide,setHeroSlide]=useState(0);
  const path=location.pathname,detail=path.startsWith('/propiedades/'),development=path.startsWith('/fraccionamientos/'),mapMode=path==='/mapa',home=path==='/',developmentsPage=path==='/fraccionamientos',aboutPage=path==='/nosotros';
  useEffect(()=>{let live=true;setLoading(true);api<Catalog>('/api/catalog').then(d=>{if(live){setData(d);setError('');}}).catch(()=>{if(live)setError('Estamos preparando el catálogo. Vuelve a consultar en unos momentos.');}).finally(()=>{if(live)setLoading(false);});return()=>{live=false;};},[retry]);
  const settings=data.settings,heroImages=settings.heroImages.length?settings.heroImages:[hero],activeHero=heroSlide%heroImages.length;
  useEffect(()=>{if(settings.heroMode!=='Carrusel'||heroImages.length<2)return;const timer=window.setInterval(()=>setHeroSlide(x=>(x+1)%heroImages.length),6500);return()=>window.clearInterval(timer);},[settings.heroMode,heroImages.length]);
  const filtered=data.properties.filter(p=>(!operation||p.operation===operation)&&(!type||p.type===type)&&(!max||p.price<=Number(max))&&`${p.title} ${p.address}`.toLowerCase().includes(q.toLowerCase()));
  const property=data.properties.find(p=>p.id===path.split('/')[2]),dev=data.developments.find(p=>p.id===path.split('/')[2]),devLots=data.lots.filter(l=>l.developmentId===dev?.id),shownLots=devLots.filter(l=>lotStatus==='Todos'||l.status===lotStatus);
  const state=loading?<div className="empty" role="status">Cargando catálogo…</div>:error?<div className="empty" role="status"><p>{error}</p><button className="text-button" onClick={()=>setRetry(x=>x+1)}>Volver a consultar</button></div>:null;
  return <><header className="public-header"><Brand/><button className="mobile-menu" onClick={()=>setMenu(!menu)} aria-expanded={menu} aria-controls="public-nav">Menú</button><nav id="public-nav" className={menu?'open':''}><a aria-current={home?'page':undefined} href="/">Inicio</a><a aria-current={path==='/propiedades'?'page':undefined} href="/propiedades">Propiedades</a><a aria-current={mapMode?'page':undefined} href="/mapa">Mapa</a><a aria-current={developmentsPage?'page':undefined} href="/fraccionamientos">Fraccionamientos</a><a aria-current={aboutPage?'page':undefined} href="/nosotros">Nosotros</a></nav><a className="admin-access" href="/api/admin/me">Acceso al equipo <span aria-hidden>↗</span></a></header>
  <main>
    {home&&<section className="home-intro editorial-hero"><div className="intro-photo" style={{'--hero-position-desktop':settings.imagePositionDesktop,'--hero-position-mobile':settings.imagePositionMobile} as CSSProperties}><img key={heroImages[activeHero]} src={heroImages[activeHero]} alt="Propiedad destacada por Casa Mexino"/>{!settings.heroImages.length&&<span className="image-caption">Imagen ilustrativa</span>}{settings.heroMode==='Carrusel'&&heroImages.length>1&&<div className="hero-dots" aria-label="Imágenes de portada">{heroImages.map((_,i)=><button key={i} className={i===activeHero?'active':''} onClick={()=>setHeroSlide(i)} aria-label={`Ver imagen ${i+1}`} aria-current={i===activeHero}/>)}</div>}</div><div className="intro-copy"><p className="eyebrow">CASA MEXINO · GESTIÓN INMOBILIARIA</p><h1>{settings.heroTitle}<br/><em>{settings.heroAccent}</em></h1><p className="hero-description">{settings.heroDescription}</p><div className="hero-actions"><a className="button" href={settings.primaryUrl}>{settings.primaryLabel} <span aria-hidden="true">↗</span></a><a className="hero-map-link" href={settings.secondaryUrl}>{settings.secondaryLabel}</a></div><div className="hero-services" aria-label="Servicios"><span>Venta</span><span>Renta</span><span>Terrenos</span><span>Fraccionamientos</span></div><div className="hero-footnote"><span>ATENCIÓN LOCAL</span><span>{settings.address||'Matehuala · San Luis Potosí'}</span></div></div></section>}

    {(home||path==='/propiedades'||mapMode)&&<section id="catalogo" className={'catalog-section '+(mapMode?'wide':'')}><div className="section-top"><div><p className="eyebrow">ENCUENTRA TU ESPACIO</p><h1>{mapMode?'Matehuala, punto por punto.':home?'Encuentra tu próximo espacio':'Propiedades'}</h1></div><div className="view-toggle"><a className={!mapMode?'active':''} href="/propiedades">Lista</a><a className={mapMode?'active':''} href="/mapa">Mapa</a></div></div>
      <div className="filters"><div className="segmented" aria-label="Operación">{['','Venta','Renta'].map(v=><button key={v} aria-pressed={operation===v} className={operation===v?'active':''} onClick={()=>setOperation(v)}>{v||'Todas'}</button>)}</div><label className="sr-only" htmlFor="type">Tipo de propiedad</label><select id="type" value={type} onChange={e=>setType(e.target.value)}><option value="">Todos los tipos</option>{['Casa','Local','Terreno'].map(v=><option key={v}>{v}</option>)}</select><label className="sr-only" htmlFor="query">Buscar zona o propiedad</label><input id="query" placeholder="Zona o propiedad" value={q} onChange={e=>setQ(e.target.value)}/><label className="sr-only" htmlFor="max">Precio máximo</label><input id="max" type="number" min="0" placeholder="Hasta $ MXN" value={max} onChange={e=>setMax(e.target.value)}/>{(q||type||operation||max)&&<button className="text-button" onClick={()=>{setQ('');setType('');setOperation('');setMax('');}}>Limpiar</button>}</div>
      {mapMode?<div className="map-layout"><div><Suspense fallback={<div className="empty">Cargando mapa…</div>}><MapView properties={filtered}/></Suspense><p className="muted">{filtered.filter(p=>p.lat!==null&&p.lng!==null).length} propiedades con ubicación · Las propiedades sin coordenadas se muestran en la lista.</p></div><aside className="map-results">{state||<><p className="count">{filtered.length} resultados</p>{filtered.map(p=><PropertyCard key={p.id} p={p}/>)}{!filtered.length&&<div className="empty">No hay propiedades para estos filtros.</div>}</>}</aside></div>:state||<><p className="count">{filtered.length} {filtered.length===1?'propiedad disponible':'propiedades disponibles'}</p><div className="listings-grid">{filtered.map(p=><PropertyCard p={p} key={p.id}/>)}</div>{!filtered.length&&<div className="empty"><h3>{data.properties.length?'Sin coincidencias':'Próximamente, nuevas propiedades'}</h3><p>{data.properties.length?'Prueba con otra zona, precio o tipo de inmueble.':'Aquí podrás consultar el inventario publicado por Casa Mexino.'}</p></div>}</>}
    </section>}
    {detail&&<section className="detail-section"><a className="back" href="/propiedades">← Propiedades</a>{state||(!property?<div className="empty">Esta propiedad no está publicada.</div>:<><div className="section-top"><div><p className="eyebrow">{property.operation} · {property.type} · {property.status}</p><h1>{property.title}</h1><p>{property.address}</p></div><strong className="detail-price">{money(property.price)}{property.operation==='Renta'?' / mes':''}</strong></div><div className="gallery"><img className="gallery-main" src={property.images[photo]||property.images[0]} alt={property.title}/><div className="thumbnails">{property.images.map((src,i)=><button key={src+i} className={i===photo?'active':''} onClick={()=>setPhoto(i)} aria-label={`Ver fotografía ${i+1}`}><img src={src} alt=""/></button>)}</div></div><div className="detail-columns"><article><div className="facts"><span>{property.area} m²</span>{property.bedrooms>0&&<span>{property.bedrooms} recámaras</span>}{property.bathrooms>0&&<span>{property.bathrooms} baños</span>}</div><h2>Acerca de esta propiedad</h2><p className="description">{property.description||'Descripción pendiente.'}</p></article><aside className="contact-box"><p className="eyebrow">ATENCIÓN PERSONAL</p><h2>¿Te interesa?</h2><p>Consulta disponibilidad y agenda una visita con Casa Mexino.</p><div className="contact-actions">{settings.whatsapp&&<a className="button" href={`https://wa.me/${settings.whatsapp.replace(/\D/g,'')}`} target="_blank" rel="noreferrer">Escribir por WhatsApp ↗</a>}{settings.phone&&<a href={`tel:${settings.phone.replace(/[^\d+]/g,'')}`}>{settings.phone}</a>}{settings.email&&<a href={`mailto:${settings.email}`}>{settings.email}</a>}{!settings.whatsapp&&!settings.phone&&!settings.email&&<p className="muted">Información de contacto pendiente de configurar.</p>}</div></aside></div>{property.lat!==null&&property.lng!==null&&<Suspense fallback={null}><MapView properties={[property]}/></Suspense>}</>)}</section>}
    {developmentsPage&&<section className="catalog-section"><p className="eyebrow">ESPACIO PARA CRECER</p><h1>Fraccionamientos</h1>{state||<><div className="listings-grid">{data.developments.map(d=><a className="development-card" href={`/fraccionamientos/${d.id}`} key={d.id}><span className="eyebrow">DESARROLLO</span><h2>{d.title}</h2><p>{d.address}</p><span>{data.lots.filter(l=>l.developmentId===d.id&&l.status==='Disponible').length} lotes disponibles</span><strong>Explorar lotes ↗</strong></a>)}</div>{!data.developments.length&&<div className="empty">Próximamente podrás consultar desarrollos y disponibilidad de lotes.</div>}</>}</section>}
    {aboutPage&&<section className="about-page"><div className="about-heading"><p className="eyebrow">CASA MEXINO · GESTIÓN INMOBILIARIA</p><h1>{settings.aboutTitle}</h1><p>{settings.aboutStory}</p></div><div className="about-values"><article><span>01</span><p className="eyebrow">CONOCIMIENTO LOCAL</p><h2>Experiencia que orienta</h2><p>{settings.aboutExperience}</p></article><article><span>02</span><p className="eyebrow">NUESTRO COMPROMISO</p><h2>Relaciones de confianza</h2><p>{settings.aboutMission}</p></article></div><aside className="about-contact"><div><p className="eyebrow">VISÍTANOS O CONVERSEMOS</p><h2>Estamos para ayudarte a dar el siguiente paso.</h2></div><dl><div><dt>Oficina</dt><dd>{settings.address||'Matehuala, San Luis Potosí'}</dd></div>{settings.officeHours&&<div><dt>Atención</dt><dd>{settings.officeHours}</dd></div>}{settings.phone&&<div><dt>Teléfono</dt><dd><a href={`tel:${settings.phone.replace(/[^\d+]/g,'')}`}>{settings.phone}</a></dd></div>}{settings.email&&<div><dt>Correo</dt><dd><a href={`mailto:${settings.email}`}>{settings.email}</a></dd></div>}</dl>{settings.whatsapp&&<a className="button" href={`https://wa.me/${settings.whatsapp.replace(/\D/g,'')}`} target="_blank" rel="noreferrer">Contactar por WhatsApp ↗</a>}</aside></section>}
    {development&&<section className="catalog-section development-detail"><a className="back" href="/fraccionamientos">← Fraccionamientos</a>{state||(!dev?<div className="empty">Fraccionamiento no publicado.</div>:<><div className="development-heading"><div><p className="eyebrow">{dev.address||'MATEHUALA, S.L.P.'}</p><h1>{dev.title}</h1><p className="description">{dev.description}</p></div><div className="development-summary"><span><strong>{devLots.filter(l=>l.status==='Disponible').length}</strong> disponibles</span><span><strong>{devLots.filter(l=>l.status==='Apartado').length}</strong> apartados</span><span><strong>{devLots.filter(l=>l.status==='Vendido').length}</strong> vendidos</span></div></div><div className="availability-toolbar"><div><strong>Disponibilidad</strong><p>Selecciona un lote en el plano o en la lista.</p></div><div className="segmented">{['Todos','Disponible','Apartado','Vendido'].map(s=><button key={s} className={lotStatus===s?'active':''} onClick={()=>{setLotStatus(s);setSelectedLot(null);}}>{s}</button>)}</div></div><div className="legend"><span className="available">Disponible</span><span className="reserved">Apartado</span><span className="sold">Vendido</span></div><div className="plan-layout"><PlanView plan={dev.plan} lots={shownLots} selected={selectedLot?.id} onSelect={setSelectedLot}/><aside className="lot-details">{selectedLot?<><p className="eyebrow">MANZANA {selectedLot.block}</p><h2>Lote {selectedLot.number}</h2><span className={'pill lot-status '+selectedLot.status.toLowerCase()}>{selectedLot.status}</span><dl><div><dt>Superficie</dt><dd>{selectedLot.area} m²</dd></div><div><dt>Precio</dt><dd>{money(selectedLot.price)}</dd></div></dl>{selectedLot.status==='Disponible'&&settings.whatsapp&&<a className="button" href={`https://wa.me/${settings.whatsapp.replace(/\D/g,'')}`} target="_blank" rel="noreferrer">Solicitar información ↗</a>}</>:<><p className="eyebrow">CONSULTA DE LOTES</p><h2>{shownLots.length} resultados</h2><p>Elige un lote para consultar superficie, precio y disponibilidad.</p></>}</aside></div><div className="public-lot-grid">{shownLots.map(l=><button key={l.id} className={(l.id===selectedLot?.id?'selected ':'')+l.status.toLowerCase()} onClick={()=>setSelectedLot(l)}><span>M{l.block} · L{l.number}</span><small>{l.area} m²</small><strong>{l.status==='Disponible'?money(l.price):l.status}</strong></button>)}</div>{!shownLots.length&&<div className="empty">No hay lotes con este estado.</div>}</>)}</section>}
    {!home&&!detail&&!development&&!developmentsPage&&!mapMode&&!aboutPage&&path!=='/propiedades'&&<div className="empty"><h1>Página no encontrada</h1><a href="/">Volver al inicio</a></div>}
  </main><footer className="public-footer"><Brand/><p>{settings.address||'Matehuala, San Luis Potosí'}</p><span>© {new Date().getFullYear()} Casa Mexino</span></footer></>;
}
