import {useEffect,useState,lazy,Suspense} from 'react';
import type {Catalog,Property,Lot} from './model';
import {emptyCatalog,money} from './model';
import {api} from './api';
import hero from './assets/hero-casa.webp';
import PlanView from './PlanView';
const MapView=lazy(()=>import('./MapView'));
export function Brand(){return <a className="brand" href="/" aria-label="Casa Mexino, inicio"><img className="brand-logo" src="/logo-casa-mexino.png?v=2" alt="Casa Mexino · Gestión Inmobiliaria"/></a>;}
function PropertyCard({p}:{p:Property}){return <a className="listing" href={`/propiedades/${p.id}`}><div className="listing-photo">{p.images[0]?<img src={p.images[0]} alt={p.title} loading="lazy"/>:<span>Sin fotografía</span>}<span className="tag">{p.operation} · {p.type}</span>{p.status!=='Disponible'&&<span className="status-tag">{p.status}</span>}</div><div className="listing-heading"><h3>{p.title}</h3><span aria-hidden>↗</span></div><p>{p.address||'Matehuala'}</p><div className="listing-bottom"><strong>{money(p.price)}{p.operation==='Renta'&&<small> / mes</small>}</strong><span>{p.area} m²</span></div></a>;}
export default function PublicPortal(){
  const [data,setData]=useState<Catalog>(emptyCatalog),[loading,setLoading]=useState(true),[error,setError]=useState(''),[retry,setRetry]=useState(0);
  const [q,setQ]=useState(''),[operation,setOperation]=useState(''),[type,setType]=useState(''),[max,setMax]=useState(''),[menu,setMenu]=useState(false),[selectedLot,setSelectedLot]=useState<Lot|null>(null),[photo,setPhoto]=useState(0);
  const path=location.pathname,detail=path.startsWith('/propiedades/'),development=path.startsWith('/fraccionamientos/'),mapMode=path==='/mapa',home=path==='/',developmentsPage=path==='/fraccionamientos';
  useEffect(()=>{let live=true;setLoading(true);api<Catalog>('/api/catalog').then(d=>{if(live){setData(d);setError('');}}).catch(()=>{if(live)setError('Estamos preparando el catálogo. Vuelve a consultar en unos momentos.');}).finally(()=>{if(live)setLoading(false);});return()=>{live=false;};},[retry]);
  const filtered=data.properties.filter(p=>(!operation||p.operation===operation)&&(!type||p.type===type)&&(!max||p.price<=Number(max))&&`${p.title} ${p.address}`.toLowerCase().includes(q.toLowerCase()));
  const property=data.properties.find(p=>p.id===path.split('/')[2]),dev=data.developments.find(p=>p.id===path.split('/')[2]);
  const state=loading?<div className="empty" role="status">Cargando catálogo…</div>:error?<div className="empty" role="status"><p>{error}</p><button className="text-button" onClick={()=>setRetry(x=>x+1)}>Volver a consultar</button></div>:null;
  return <><header className="public-header"><Brand/><button className="mobile-menu" onClick={()=>setMenu(!menu)} aria-expanded={menu} aria-controls="public-nav">Menú</button><nav id="public-nav" className={menu?'open':''}><a aria-current={home?'page':undefined} href="/">Inicio</a><a aria-current={path==='/propiedades'?'page':undefined} href="/propiedades">Propiedades</a><a aria-current={mapMode?'page':undefined} href="/mapa">Mapa</a><a aria-current={developmentsPage?'page':undefined} href="/fraccionamientos">Fraccionamientos</a></nav><a className="admin-access" href="/admin">Acceso al equipo <span aria-hidden>↗</span></a></header>
  <main>
    {home&&<section className="home-intro editorial-hero"><div className="intro-photo"><img src={hero} alt="Arquitectura residencial contemporánea, imagen ilustrativa"/><span className="image-caption">Imagen ilustrativa</span></div><div className="intro-copy"><p className="eyebrow">CASA MEXINO / MATEHUALA, S.L.P.</p><h1>Un nuevo lugar.<br/><em>Más posibilidades.</em></h1><p className="hero-description">Encuentra casa, un espacio para tu negocio o el terreno donde empieza tu próximo proyecto.</p><div className="hero-actions"><a className="button" href="#catalogo">Encuentra tu propiedad <span aria-hidden="true">↗</span></a><a className="hero-map-link" href="/mapa">Explorar por ubicación</a></div><div className="hero-footnote"><span>VENTA & RENTA</span><span>Matehuala · Altiplano Potosino</span></div></div></section>}

    {(home||path==='/propiedades'||mapMode)&&<section id="catalogo" className={'catalog-section '+(mapMode?'wide':'')}><div className="section-top"><div><p className="eyebrow">ENCUENTRA TU ESPACIO</p><h1>{mapMode?'Matehuala, punto por punto.':home?'Encuentra tu próximo espacio':'Propiedades'}</h1></div><div className="view-toggle"><a className={!mapMode?'active':''} href="/propiedades">Lista</a><a className={mapMode?'active':''} href="/mapa">Mapa</a></div></div>
      <div className="filters"><div className="segmented" aria-label="Operación">{['','Venta','Renta'].map(v=><button key={v} aria-pressed={operation===v} className={operation===v?'active':''} onClick={()=>setOperation(v)}>{v||'Todas'}</button>)}</div><label className="sr-only" htmlFor="type">Tipo de propiedad</label><select id="type" value={type} onChange={e=>setType(e.target.value)}><option value="">Todos los tipos</option>{['Casa','Local','Terreno'].map(v=><option key={v}>{v}</option>)}</select><label className="sr-only" htmlFor="query">Buscar zona o propiedad</label><input id="query" placeholder="Zona o propiedad" value={q} onChange={e=>setQ(e.target.value)}/><label className="sr-only" htmlFor="max">Precio máximo</label><input id="max" type="number" min="0" placeholder="Hasta $ MXN" value={max} onChange={e=>setMax(e.target.value)}/>{(q||type||operation||max)&&<button className="text-button" onClick={()=>{setQ('');setType('');setOperation('');setMax('');}}>Limpiar</button>}</div>
      {mapMode?<div className="map-layout"><div><Suspense fallback={<div className="empty">Cargando mapa…</div>}><MapView properties={filtered}/></Suspense><p className="muted">{filtered.filter(p=>p.lat!==null&&p.lng!==null).length} propiedades con ubicación · Las propiedades sin coordenadas se muestran en la lista.</p></div><aside className="map-results">{state||<><p className="count">{filtered.length} resultados</p>{filtered.map(p=><PropertyCard key={p.id} p={p}/>)}{!filtered.length&&<div className="empty">No hay propiedades para estos filtros.</div>}</>}</aside></div>:state||<><p className="count">{filtered.length} {filtered.length===1?'propiedad disponible':'propiedades disponibles'}</p><div className="listings-grid">{filtered.map(p=><PropertyCard p={p} key={p.id}/>)}</div>{!filtered.length&&<div className="empty"><h3>{data.properties.length?'Sin coincidencias':'Próximamente, nuevas propiedades'}</h3><p>{data.properties.length?'Prueba con otra zona, precio o tipo de inmueble.':'Aquí podrás consultar el inventario publicado por Casa Mexino.'}</p></div>}</>}
    </section>}
    {detail&&<section className="detail-section"><a className="back" href="/propiedades">← Propiedades</a>{state||(!property?<div className="empty">Esta propiedad no está publicada.</div>:<><div className="section-top"><div><p className="eyebrow">{property.operation} · {property.type} · {property.status}</p><h1>{property.title}</h1><p>{property.address}</p></div><strong className="detail-price">{money(property.price)}{property.operation==='Renta'?' / mes':''}</strong></div><div className="gallery"><img className="gallery-main" src={property.images[photo]||property.images[0]} alt={property.title}/><div className="thumbnails">{property.images.map((src,i)=><button key={src+i} className={i===photo?'active':''} onClick={()=>setPhoto(i)} aria-label={`Ver fotografía ${i+1}`}><img src={src} alt=""/></button>)}</div></div><div className="detail-columns"><article><div className="facts"><span>{property.area} m²</span>{property.bedrooms>0&&<span>{property.bedrooms} recámaras</span>}{property.bathrooms>0&&<span>{property.bathrooms} baños</span>}</div><h2>Acerca de esta propiedad</h2><p className="description">{property.description||'Descripción pendiente.'}</p></article><aside className="contact-box"><h2>¿Te interesa?</h2><p>Consulta disponibilidad y agenda una visita con Casa Mexino.</p><p className="muted">Información de contacto pendiente de confirmar.</p></aside></div>{property.lat!==null&&property.lng!==null&&<Suspense fallback={null}><MapView properties={[property]}/></Suspense>}</>)}</section>}
    {developmentsPage&&<section className="catalog-section"><p className="eyebrow">ESPACIO PARA CRECER</p><h1>Fraccionamientos</h1>{state||<><div className="listings-grid">{data.developments.map(d=><a className="development-card" href={`/fraccionamientos/${d.id}`} key={d.id}><span className="eyebrow">DESARROLLO</span><h2>{d.title}</h2><p>{d.address}</p><span>{data.lots.filter(l=>l.developmentId===d.id&&l.status==='Disponible').length} lotes disponibles</span><strong>Explorar lotes ↗</strong></a>)}</div>{!data.developments.length&&<div className="empty">Próximamente podrás consultar desarrollos y disponibilidad de lotes.</div>}</>}</section>}
    {development&&<section className="catalog-section"><a className="back" href="/fraccionamientos">← Fraccionamientos</a>{state||(!dev?<div className="empty">Fraccionamiento no publicado.</div>:<><p className="eyebrow">{dev.address}</p><h1>{dev.title}</h1><p className="description">{dev.description}</p><div className="legend"><span className="available">Disponible</span><span className="reserved">Apartado</span><span className="sold">Vendido</span></div><div className="plan-layout"><PlanView plan={dev.plan} lots={data.lots.filter(l=>l.developmentId===dev.id)} selected={selectedLot?.id} onSelect={setSelectedLot}/><aside className="lot-details">{selectedLot?<><p className="eyebrow">MANZANA {selectedLot.block}</p><h2>Lote {selectedLot.number}</h2><span className="pill">{selectedLot.status}</span><p>{selectedLot.area} m²</p><strong>{money(selectedLot.price)}</strong></>:<p>Selecciona un lote en el plano o en la lista.</p>}</aside></div><div className="lot-buttons">{data.lots.filter(l=>l.developmentId===dev.id).map(l=><button key={l.id} onClick={()=>setSelectedLot(l)}>M{l.block} · L{l.number} <small>{l.status}</small></button>)}</div></>)}</section>}
    {!home&&!detail&&!development&&!developmentsPage&&!mapMode&&path!=='/propiedades'&&<div className="empty"><h1>Página no encontrada</h1><a href="/">Volver al inicio</a></div>}
  </main><footer className="public-footer"><Brand/><p>Matehuala, San Luis Potosí</p><span>© {new Date().getFullYear()} Casa Mexino</span></footer></>;
}
